name: classicmodels_modeling
version: '1.0.0'
config-version: 2

profile: classicmodels_modeling

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

vars:
  source_schema: classicmodels
  surrogate_key_treat_nulls_as_empty_strings: true

models:
  classicmodels_modeling:
    staging:
      +materialized: view
      +schema: staging
    marts:
      star_schema:
        +materialized: table
        +schema: star_schema
      obt:
        +materialized: table
        +schema: obt

seeds:
  classicmodels_modeling:
    +schema: classicmodels
    +quote_columns: false
